export default {
	SET_MESSAGE: 'SET_MESSAGE',
	SET_WHEN: 'SET_WHEN',
	SET_AUTHOR: 'SET_AUTHOR',
	SET_TODO: 'SET_TODO',
	SET_FIND_TODO_ID: 'SET_FIND_TODO_ID',
	SET_DELETE_TODO_ID: 'SET_DELETE_TODO_ID',
	ADD_TO_LOG: 'ADD_TO_LOG',
	SET_LOADING_MESSAGE: 'SET_LOADING_MESSAGE',
	SET_SHOULD_NOT_GET_TODO_ON_MOUNT: 'SET_SHOULD_NOT_GET_TODO_ON_MOUNT'
};
