export default {
	SET_TODO_MESSAGE: 'SET_TODO_MESSAGE',
	SET_WHEN: 'SET_WHEN',
	SET_AUTHOR: 'SET_AUTHOR',
	SET_NUMBER: 'SET_NUMBER',
	SET_TODO: 'SET_TODO',
	INCREMENT_NUMBER: 'INCREMENT_NUMBER',
	DECREMENT_NUMBER: 'DECREMENT_NUMBER',
	SET_LOADING_MESSAGE: 'SET_LOADING_MESSAGE'
};
