export default {
	SET_ADD_MESSAGE: 'SET_ADD_MESSAGE',
	SET_ADD_WHEN: 'SET_ADD_WHEN',
	SET_ADD_AUTHOR: 'SET_ADD_AUTHOR',
	SET_TODO: 'SET_TODO',
	SET_GET_ID: 'SET_GET_ID',
	SET_DELETE_ID: 'SET_DELETE_ID',
	ADD_TO_LOG: 'ADD_TO_LOG',
	SET_LOADING_MESSAGE: 'SET_LOADING_MESSAGE',
	SET_SHOULD_NOT_GET_TODO_ON_MOUNT: 'SET_SHOULD_NOT_GET_TODO_ON_MOUNT'
};
